name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Compile
        run: javac VoucherCalculator.java VoucherCalculatorTest.java

      - name: Run Test
        run: java VoucherCalculatorTest
